export interface IMapData {
	krasnoyarsk?: string
	eniseysk?: string
	achinsk?: string
	turukhanskij_rajon?: string
	minusinskij_rajon?: string
	ermakovskij_rajon?: string
	evenkiyskiy?: string
	shushenskij_rajon?: string
	taseevskij_rajon?: string
	achinskij_rajon?: string
	sharypovskij_rajon?: string
	kansk?: string
	minusinsk?: string
	bogotolskij_rajon?: string
	norilsk?: string
	sharypovo?: string
	lesosibirsk?: string
	nazarovo?: string
	rybinskij_rajon?: string
	tajmyrskaja?: string
	emeljanovskij_rajon?: string
	borodino?: string
	enisejskij_rajon?: string
	bolshemurtinskij_rajon?: string
	balakhtinskij_rajon?: string
	kedrovyj?: string
	irbejskij_rajon?: string
	sajanskij_rajon?: string
	boguchanskij_rajon?: string
	abanskij_rajon?: string
	kazachinskij_rajon?: string
	kuraginskij_rajon?: string
	kozulskij_rajon?: string
	manskij_rajon?: string
	berezovskij_rajon?: string
	sukhobuzimskij_rajon?: string
	ujarskij_rajon?: string
	kanskij_rajon?: string
	nizhneingashskij_rajon?: string
	partizanskij_rajon?: string
	krasnoturanskij_rajon?: string
	dzerzhinskij_rajon?: string
	karatuzskij_rajon?: string
	divnogorsk?: string
	tjukhtetskij_rajon?: string
	ilanskij_rajon?: string
	kezhemskij_rajon?: string
	biriljusskij_rajon?: string
	novoselovskij_rajon?: string
	motyginskij_rajon?: string
	sosnovoborsk?: string
	idrinskij_rajon?: string
	uzhurskij_rajon?: string
	pirovskij_rajon?: string
	bolsheulujskij_rajon?: string
	nazarovskij_rajon?: string
	severoenisejskij_rajon?: string
	zato_solnechnyj?: string
	zelenogorsk?: string
	tungusskochunskaja?: string
	bajkitskaja?: string
	bogotol?: string
}

export const generateDataMap = (color: string) => {
	return {
		krasnoyarsk: color,
		eniseysk: color,
		achinsk: color,
		turukhanskij_rajon: color,
		minusinskij_rajon: color,
		ermakovskij_rajon: color,
		evenkiyskiy: color,
		shushenskij_rajon: color,
		taseevskij_rajon: color,
		achinskij_rajon: color,
		sharypovskij_rajon: color,
		kansk: color,
		minusinsk: color,
		bogotolskij_rajon: color,
		bogotol: color,
		norilsk: color,
		sharypovo: color,
		lesosibirsk: color,
		nazarovo: color,
		rybinskij_rajon: color,
		tajmyrskaja: color,
		emeljanovskij_rajon: color,
		borodino: color,
		enisejskij_rajon: color,
		bolshemurtinskij_rajon: color,
		balakhtinskij_rajon: color,
		kedrovyj: color,
		irbejskij_rajon: color,
		sajanskij_rajon: color,
		boguchanskij_rajon: color,
		abanskij_rajon: color,
		kazachinskij_rajon: color,
		kuraginskij_rajon: color,
		kozulskij_rajon: color,
		manskij_rajon: color,
		berezovskij_rajon: color,
		sukhobuzimskij_rajon: color,
		ujarskij_rajon: color,
		kanskij_rajon: color,
		nizhneingashskij_rajon: color,
		partizanskij_rajon: color,
		krasnoturanskij_rajon: color,
		dzerzhinskij_rajon: color,
		karatuzskij_rajon: color,
		divnogorsk: color,
		tjukhtetskij_rajon: color,
		ilanskij_rajon: color,
		kezhemskij_rajon: color,
		biriljusskij_rajon: color,
		novoselovskij_rajon: color,
		motyginskij_rajon: color,
		sosnovoborsk: color,
		idrinskij_rajon: color,
		uzhurskij_rajon: color,
		pirovskij_rajon: color,
		bolsheulujskij_rajon: color,
		nazarovskij_rajon: color,
		severoenisejskij_rajon: color,
		zato_solnechnyj: color,
		zelenogorsk: color,
		tungusskochunskaja: color,
		bajkitskaja: color,
	}
}
